@startditaa
/-------------------------\
|            +---------+  |
|  request   : a ... b |  |
|            +---------+  |
|               |...|     |
|               v   v     |
|            +-+-------+  |
|  container : x ... y |  |
|            +---------+  |
\-------------------------/
    fitness of candidate
@endditaa